### ISSUE TITLE
Use register of local authorities in register

### ISSUE THREAD

**Issue by symroe** [openregister/jobcentre-data#7]
(I get that this isn't finished yet!)

https://github.com/openregister/jobcentre-data/blob/master/data/jobcentre-district/jobcentre-district.csv

Seems to contain a column with local authority values that are a) names not IDs and b) don't exist as local authorities according to the register.

If it's the case that the districts don't conform to local authorities then I suggest renaming that field to indicate it. If they should map to LAs then the IDs should be used rather than name.

**Comment by nacnudus** [comment]
Thanks @symroe 

It has got a bit untidy in that directory.  The file we're using is https://github.com/openregister/jobcentre-data/blob/master/data/jobcentre-district/data.tsv.  But there is a separate issue with that file, which is that several districts are missing.  We're working on it!

It turned out to be wishful thinking that jobcentres would link to local authorities, so register won't link to local authorities.  The current [alpha](https://jobcentre-district.alpha.openregister.org/) omits that column.

**Comment by symroe** [comment]
That's great, thanks!
